name: 'user_srv'

# Nacos
host: '10.120.21.77'
port: 8848
namespace: '73bb8093-63eb-4bf3-bd81-84b18fe259d6'
user: 'nacos'
password: 'nacos'
data_id: 'user-srv.json'
group: 'dev'

mysql:
  host: '10.120.21.77'
  port: 3306
  user: 'root'
  password: '123456'
  db: 'shop_user_srv'

consul:
  host: '10.120.21.77'
  port: 8500